<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Icon</name>
   <tag></tag>
   <elementGuidId>01a0599f-61a8-4efc-a9cf-61d9c555ac02</elementGuidId>
   <imagePath>C:\Users\Krishna\Desktop\Edit_Icon.JPG</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\Krishna\Desktop\Edit_Icon.JPG</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
