<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Invite_MuiAvatar-img css-1hy9t21</name>
   <tag></tag>
   <elementGuidId>cb7e566a-3626-44f8-80e4-0f6547a1f4ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.MuiAvatar-img.css-1hy9t21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/header/div/div[3]/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>adcc6a79-d498-43cd-8984-f3fd44de0577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Remy Sharp</value>
      <webElementGuid>bab14a54-6916-4c64-ad6a-5236582ee128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://firebasestorage.googleapis.com/v0/b/nachpayptai-dev.appspot.com/o/CompanyLogo%2F1675840394CompanuLogo1675840394915Uth%20uk%20logo.gif?alt=media&amp;token=d663b018-5892-498e-9cf6-abe83f7ce05a</value>
      <webElementGuid>54948ff6-2c24-48cd-97d5-a08c1b7abee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-img css-1hy9t21</value>
      <webElementGuid>d8c80dfc-1bd3-499f-b903-e2f7416cba57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-hboir5&quot;]/div[@class=&quot;MuiBox-root css-1stk98t&quot;]/div[@class=&quot;navbar MuiBox-root css-1ck4cv3&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation4 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionStatic css-1x7skt0&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular css-i6s8oy&quot;]/div[@class=&quot;MuiBox-root css-70qvj9&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-circular css-85ur4f&quot;]/img[@class=&quot;MuiAvatar-img css-1hy9t21&quot;]</value>
      <webElementGuid>f91092cf-40b1-4ff9-9280-05bd2521fa56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/header/div/div[3]/div[3]/img</value>
      <webElementGuid>4f61c00a-3219-4e58-99f4-c1a690fd410a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Remy Sharp']</value>
      <webElementGuid>b0e706e6-e108-464b-9ad2-f80572d862f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>43ac7fc4-291c-44ca-82e5-d6b3bb17b99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Remy Sharp' and @src = 'https://firebasestorage.googleapis.com/v0/b/nachpayptai-dev.appspot.com/o/CompanyLogo%2F1675840394CompanuLogo1675840394915Uth%20uk%20logo.gif?alt=media&amp;token=d663b018-5892-498e-9cf6-abe83f7ce05a']</value>
      <webElementGuid>a537033c-9f7b-47f0-8719-750058f2fd09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
