<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank_Profile_mainbranch_dropdown</name>
   <tag></tag>
   <elementGuidId>42381b1f-27e7-47e4-897f-8dbd4a221231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;demo-simple-select-standard&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>2f4dac47-cee8-4af7-984a-eeff20843ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard Working Capital ReceivablesPayablesSettlementsInsuranceTredsReportsBeta Version 1.0​Uth Uk Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number12345695 Branch IFSCYESB0000653Account TypeSB  MICR890765432 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameTest  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameATBMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameJuMOrJ  Account Number532164098 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameSubbranchMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameAxHnZL  Account Number872730773 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameSubbranchMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]Ajay Pajay@uth-uk.com+919008702931User ManagementSign Out  Uth UkBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch cnIR OyJr hvfp</value>
      <webElementGuid>8e1e75ee-f15b-4752-874e-2d99d19eac39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>ad93654f-8989-4c12-8504-a7c2e4024e21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>6c83b3b4-8408-40fd-b824-d7a2c83d5a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'Dashboard Working Capital ReceivablesPayablesSettlementsInsuranceTredsReportsBeta Version 1.0​Uth Uk Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number12345695 Branch IFSCYESB0000653Account TypeSB  MICR890765432 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameTest  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameATBMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameJuMOrJ  Account Number532164098 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameSubbranchMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameAxHnZL  Account Number872730773 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameSubbranchMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]Ajay Pajay@uth-uk.com+919008702931User ManagementSign Out  Uth UkBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch cnIR OyJr hvfp' or . = 'Dashboard Working Capital ReceivablesPayablesSettlementsInsuranceTredsReportsBeta Version 1.0​Uth Uk Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number12345695 Branch IFSCYESB0000653Account TypeSB  MICR890765432 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameTest  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameATBMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameJuMOrJ  Account Number532164098 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameSubbranchMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameAxHnZL  Account Number872730773 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameSubbranchMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]Ajay Pajay@uth-uk.com+919008702931User ManagementSign Out  Uth UkBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch cnIR OyJr hvfp')]</value>
      <webElementGuid>60a2c945-8049-4664-9a01-a59a2e85f752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
