<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sent</name>
   <tag></tag>
   <elementGuidId>ee9fb0e1-f0e6-4a53-9368-4fb65cdaa9b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='simple-tab-0'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiTabs-scroller.MuiTabs-fixed.css-1anid1y > div.MuiTabs-flexContainer.css-k008qs > #simple-tab-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97b0902a-d160-4d97-8f91-23e876e7144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-1q2h7u5</value>
      <webElementGuid>5da0ff0e-529f-4ac6-b533-8fea101ef5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ada7b094-15d7-42b9-b908-dd705b6c8ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b1f3846-44a4-40df-b644-300f5c26e060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>41e33f78-41d8-4388-be69-ae127881945f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>33674baf-658a-4ff4-8490-9301a8f969c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simple-tab-0</value>
      <webElementGuid>ae78172d-f3cb-48ce-9ec1-326d3eace1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>simple-tabpanel-0</value>
      <webElementGuid>9d5ccf72-b602-48f1-a904-61676757d09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sent</value>
      <webElementGuid>338ba352-f949-46a0-b244-be057f3450b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-hboir5&quot;]/div[@class=&quot;MuiBox-root css-1stk98t&quot;]/div[@class=&quot;MuiBox-root css-nwok3i&quot;]/div[@class=&quot;tab-container-Box MuiBox-root css-ajghaq&quot;]/div[@class=&quot;profile MuiBox-root css-1v8x7dw&quot;]/div[@id=&quot;simple-tabpanel-0&quot;]/div[@class=&quot;MuiBox-root css-mez6zq&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 css-ahj2mt-MuiTypography-root&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;automated&quot;]/div[@class=&quot;MuiBox-root css-1als04x&quot;]/div[@class=&quot;MuiTabs-root css-orq8zk&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-fixed css-1anid1y&quot;]/div[@class=&quot;MuiTabs-flexContainer css-k008qs&quot;]/button[@id=&quot;simple-tab-0&quot;]</value>
      <webElementGuid>9453ac22-6762-4578-8a5d-ba5418f47592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='simple-tab-0'])[2]</value>
      <webElementGuid>1138ccfe-3221-4921-8b02-910dcfcdbd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simple-tabpanel-0']/div/p/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>4b394708-b823-4cb1-805b-a7810107539d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Received'])[1]/following::button[1]</value>
      <webElementGuid>0ddedcbd-22ec-48d6-84bb-65315d77d55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requests'])[1]/following::button[2]</value>
      <webElementGuid>260d9f9b-52bb-40a3-8bd2-817435452418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sent']/parent::*</value>
      <webElementGuid>393ece5c-5215-4c0f-ac02-0abddae9bb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>c8f597b4-4ec1-458c-90d3-0e8766d57b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'simple-tab-0' and (text() = 'Sent' or . = 'Sent')]</value>
      <webElementGuid>7a8876e7-d2aa-4bd2-b117-3a1856fbbb93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
