<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainBranch_dropdown_bankProfile</name>
   <tag></tag>
   <elementGuidId>4f3b0e34-87d2-4d78-b3b8-0e4f0a7222b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;demo-simple-select-standard&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Dashboard Working Capital ReceivablesPayablesSettlementsReportsInsuranceTredsBeta Version 1.0​UTH Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number28451234 Branch IFSCYESB0000653Account TypeCA  MICR560532002 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameChaigudda  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameDTHMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]UTH PTuthukpnt@gmail.com+918553619133User ManagementSign Out  UTHBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch' or . = 'Dashboard Working Capital ReceivablesPayablesSettlementsReportsInsuranceTredsBeta Version 1.0​UTH Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number28451234 Branch IFSCYESB0000653Account TypeCA  MICR560532002 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameChaigudda  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameDTHMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]UTH PTuthukpnt@gmail.com+918553619133User ManagementSign Out  UTHBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>03dc3756-a235-49ba-9060-2ebec2e7a0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard Working Capital ReceivablesPayablesSettlementsReportsInsuranceTredsBeta Version 1.0​UTH Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number28451234 Branch IFSCYESB0000653Account TypeCA  MICR560532002 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameChaigudda  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameDTHMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]UTH PTuthukpnt@gmail.com+918553619133User ManagementSign Out  UTHBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch</value>
      <webElementGuid>33b791ca-9fb4-4588-a01c-c41fd4319b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>9a7fde40-3150-4cc2-bae7-1f7d107cb5ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>0adb2f99-6542-4850-a716-fcf8ec4c0cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'Dashboard Working Capital ReceivablesPayablesSettlementsReportsInsuranceTredsBeta Version 1.0​UTH Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number28451234 Branch IFSCYESB0000653Account TypeCA  MICR560532002 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameChaigudda  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameDTHMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]UTH PTuthukpnt@gmail.com+918553619133User ManagementSign Out  UTHBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch' or . = 'Dashboard Working Capital ReceivablesPayablesSettlementsReportsInsuranceTredsBeta Version 1.0​UTH Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number28451234 Branch IFSCYESB0000653Account TypeCA  MICR560532002 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameChaigudda  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameDTHMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]UTH PTuthukpnt@gmail.com+918553619133User ManagementSign Out  UTHBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch')]</value>
      <webElementGuid>1fb32c30-6225-451f-a954-a91fcbc73795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
