package desktopDriver

import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject

import org.openqa.selenium.WebDriver

import com.kms.katalon.core.annotation.Keyword
import com.kms.katalon.core.checkpoint.Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling
import com.kms.katalon.core.testcase.TestCase
import com.kms.katalon.core.testdata.TestData
import com.kms.katalon.core.testng.keyword.TestNGBuiltinKeywords as TestNGKW
import com.kms.katalon.core.testobject.TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows

import internal.GlobalVariable
import org.openqa.selenium.WebElement as WebElement
import org.openqa.selenium.By as By
import org.openqa.selenium.WebDriver
import org.apache.commons.lang.RandomStringUtils;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.Keys as Keys



class WinFunctions{

	WebDriver driver;

	WinFunctions()
	{
		this.driver = Windows.getDriver()
	}

	void display(){
		println(driver.getTitle())
	}

	@Keyword
	void findAndClickWindowsElement(Name){
		WebElement ele = driver.findElement(By.name(Name))
		ele.click()
	}

	@Keyword
	void findAndClickWindowsElementByXpath(Xpath){
		WebElement ele = driver.findElement(By.xpath(Xpath))
		ele.click()
	}

	@Keyword
	void trial() {
		WebElement ele = driver.findElement(By.xpath('//TreeItem[@Name="MaintenanceAdmin"]/DataItem[@Name="Column0"]'));
		System.out.println("The image source is : "+ele.getAttribute("Value.Value"));
		WebElement elem = driver.findElement(By.xpath('//TreeItem[@Name="BackupAdmin"]/DataItem[@Name="Column0"]'));
		System.out.println("The BackupAdmin is : "+elem.getAttribute("Value.Value"));

	}
	
	@Keyword
	void trialtoClose() {
		WebElement element = driver.findElement(By.name("File"))
		element.sendKeys(Keys.chord(Keys.CONTROL, 'w'))
		Thread.sleep(3000)
		
//		StringBuilder keys = new StringBuilder();
//		keys.append(Keys.CONTROL);
//		keys.append(Keys.SHIFT);
//		element.sendKeys(Keys.chord(keys.toString()));
//		element.sendKeys(Keys.chord(Keys.CONTROL, 'w'))

	}

	@Keyword
	void findAndsendKeysWindowsElement(Name, value){
		WebElement ele = driver.findElement(By.name(Name))
		ele.sendKeys(value)
	}

	@Keyword
	void findAndsendKeysWindowsElementByXpath(Name, value){
		WebElement ele = driver.findElement(By.xpath(Name))
		ele.sendKeys(value)
	}


	public static String AutoGeneratedUsername(){

		int length = 5;
		boolean useLetters = true;
		boolean useNumbers = false;
		//	String generatedString = RandomStringUtils.random(length, useLetters, useNumbers).toLowerCase();
		String name = RandomStringUtils.random(length, useLetters, useNumbers).toLowerCase();
		//  System.out.println(name);

		String firstLetter = name.substring(0, 1);
		String remainingLetters = name.substring(1, name.length());

		firstLetter = firstLetter.toUpperCase();
		name = firstLetter + remainingLetters;
		System.out.println("Auto-Generated Username: " + name);
		return name.trim();

	}

	@Keyword
	void findAndsendKeysWindowsElementByXpathLogin(Name){
		WebElement ele = driver.findElement(By.xpath(Name))
		String value = AutoGeneratedUsername()
		ele.sendKeys(value)
	}


	//https://www.guru99.com/select-option-dropdown-selenium-webdriver.html
	//https://stackoverflow.com/questions/34490341/how-to-select-a-combobox-value-with-selenium-webdriver-where-its-a-div-with-rol
	@Keyword
	void selectElementValueByXpath(Xpath, value) {
		driver.findElement(By.xpath(Xpath)).sendKeys(value);
		//WebElement testDropDown = driver.findElement(By.xpath(Xpath));
		//Select dropdown = new Select(testDropDown);
		//dropdown.selectByValue(value);
		//dropdown.selectByVisibleText("Standard");
	}
}

class A{

	@Keyword
	public void toGenerateADriverInstance() {
		WinFunctions s = new WinFunctions();
		s.display();
	}
}