<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Main Branch</name>
   <tag></tag>
   <elementGuidId>63f1f7d0-bf57-4dfc-8a4e-40ee53dec957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#demo-select-small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demo-select-small']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8dc04fc-4bda-4fd1-80d7-9baad28f968f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>685bdbfb-ed92-4390-8707-6e8dca3e2161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a34daf0-cfba-4f6c-88ce-7a53c15a5bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d2b4632-6295-41d8-b33b-36920012fc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>c5f67750-c63c-4b9e-b694-aa714c86d276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>demo-select-small demo-select-small</value>
      <webElementGuid>b6beb435-9fff-467f-9cbd-f16e5c8cd003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demo-select-small</value>
      <webElementGuid>df015b72-0eb9-4fe8-bb78-eecd1db5eed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input css-11u53oe-MuiSelect-select-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>b3bdfdbb-b6d5-45ad-a30c-70e8eba16560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Main Branch</value>
      <webElementGuid>75b37a38-f424-4067-9a7c-0e1b20ec82f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-select-small&quot;)</value>
      <webElementGuid>31e60dc0-a960-46ba-85ae-ffbc8b1272eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='demo-select-small']</value>
      <webElementGuid>8620f87e-c2d5-4a2f-a9ad-17356eb826f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mui-p-71760-P-1']/div/div/div/div/div[6]/div/div</value>
      <webElementGuid>4ec8ad73-a150-4852-bb19-934886059505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[3]/following::div[4]</value>
      <webElementGuid>0e0ad079-a4a2-4e3f-9488-e59774f590ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::div[7]</value>
      <webElementGuid>3c59cb42-221a-402d-bc1a-4b6e9b41318f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[4]/preceding::div[1]</value>
      <webElementGuid>846a52a2-4576-4810-8936-eb82e58a8063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[5]/preceding::div[2]</value>
      <webElementGuid>cda201e3-f0cd-4338-bc0f-d2127feea93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Main Branch']/parent::*</value>
      <webElementGuid>e71ae689-dc00-49e5-917e-0c313df12e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]/div/div</value>
      <webElementGuid>070c2101-6f90-442d-be6c-e50c7a5b68fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'demo-select-small' and (text() = 'Main Branch' or . = 'Main Branch')]</value>
      <webElementGuid>4fd1a0bc-6a0b-47a4-af8d-06f4f4d2ff4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
